In [1]:
import os

import pandas as pd

path = "/content"

print("Dataset path:", path)

print("\nFiles in dataset:")

print(os.listdir(path))

csv_files = [f for f in os.listdir(path) if f.lower().endswith(".csv")]

if not csv_files:
    raise FileNotFoundError("No CSV file found in the dataset path.")

csv_file = csv_files[0]

print("\nCSV file:", csv_file)

df = pd.read_csv(
    os.path.join(path, csv_file),
    encoding="latin1",
    low_memory=False
)

print("\nFirst 5 rows:")

display(df.head())

print("\nLast 5 rows:")

display(df.tail())

print("\nDataset information:")

df.info()

print("\nShape:")

print(df.shape)

print("\nColumns:")

print(df.columns.tolist())

print("\nData types:")

print(df.dtypes)

print("\nStatistical description:")

display(df.describe(include="all").T)

print("\nMissing values:")

display(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate rows:")

print(df.duplicated().sum())

print("\nRestaurant names:")

display(df["Restaurant_Name"].value_counts())

print("\nCities:")

display(df["City"].value_counts())

print("\nCuisine types:")

display(df["Cuisine"].value_counts())

print("\nFood items:")

display(df["Food_Item"].value_counts())

print("\nWeather conditions:")

display(df["Weather"].value_counts())

print("\nWeekend status:")

display(df["Weekend"].value_counts())

print("\nHoliday status:")

display(df["Holiday"].value_counts())

print("\nTop restaurants based on food waste:")

display(
    df.groupby("Restaurant_Name")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print("\nTop cities based on food waste:")

display(
    df.groupby("City")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
)

print("\nTop food items based on food waste:")

display(
    df.groupby("Food_Item")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
)

print("\nCorrelation:")

display(df.corr(numeric_only=True))

df["Remaining_Quantity_Calculated"] = (
    df["Prepared_Quantity"] - df["Sold_Quantity"]
)

print("\nCalculated Remaining Quantity:")

display(
    df[
        [
            "Prepared_Quantity",
            "Sold_Quantity",
            "Remaining_Quantity_Calculated"
        ]
    ].head()
)

df["Waste_Percentage"] = (
    df["Waste_Amount_kg"] /
    df["Prepared_Quantity"]
) * 100

print("\nWaste Percentage:")

display(
    df[
        [
            "Restaurant_Name",
            "Prepared_Quantity",
            "Waste_Amount_kg",
            "Waste_Percentage"
        ]
    ].head()
)

df.to_excel(
    "food_waste_data.xlsx",
    index=False
)

df.to_json(
    "food_waste_data.json",
    orient="records",
    indent=4
)

df.to_csv(
    "food_waste_data.csv",
    index=False
)

print("\nCSV, Excel and JSON files created successfully.")

Dataset path: /content

Files in dataset:
['.config', 'Food_Waste_Prediction_Dataset.csv', 'sample_data']

CSV file: Food_Waste_Prediction_Dataset.csv

First 5 rows:

,Restaurant_ID,Restaurant_Name,City,Cuisine,Food_Item,Date,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Weather,Weekend,Holiday,Discount_Percent,Customers,Waste_Amount_kg
0,R001,Spice Garden,Chennai,South Indian,Pongal,2025-05-06,107,102,5,25,Cloudy,No,No,20,121,1.09
1,R005,Green Bowl,Mumbai,South Indian,Dosa,2025-11-29,229,198,31,29,Sunny,Yes,No,10,102,5.61
2,R002,Urban Bites,Bengaluru,Italian,Pasta,2025-05-23,89,89,0,32,Sunny,No,No,15,54,0.00
3,R004,Food Hub,Coimbatore,South Indian,Meals,2025-02-10,191,175,16,33,Cloudy,No,No,25,195,4.68
4,R003,Ocean Treat,Hyderabad,South Indian,Dosa,2025-02-21,147,113,34,33,Sunny,No,No,10,53,9.87

Last 5 rows:

,Restaurant_ID,Restaurant_Name,City,Cuisine,Food_Item,Date,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Weather,Weekend,Holiday,Discount_Percent,Customers,Waste_Amount_kg
995,R004,Food Hub,Coimbatore,South Indian,Dosa,2025-01-18,263,197,66,27,Rainy,Yes,No,5,129,17.82
996,R004,Food Hub,Coimbatore,Italian,Pasta,2025-03-07,152,99,53,29,Cloudy,No,No,0,77,15.02
997,R001,Spice Garden,Chennai,South Indian,Idli,2025-07-01,293,267,26,35,Cloudy,No,No,25,135,5.96
998,R004,Food Hub,Coimbatore,North Indian,Biryani,2025-04-04,235,164,71,38,Sunny,No,No,0,95,17.36
999,R004,Food Hub,Coimbatore,North Indian,Biryani,2025-10-29,121,92,29,25,Sunny,No,No,15,72,8.00

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Restaurant_ID       1000 non-null   object
 1   Restaurant_Name     1000 non-null   object
 2   City                1000 non-null   object
 3   Cuisine             1000 non-null   object
 4   Food_Item           1000 non-null   object
 5   Date                1000 non-null   object
 6   Prepared_Quantity   1000 non-null   int64
 7   Sold_Quantity       1000 non-null   int64
 8   Remaining_Quantity  1000 non-null   int64
 9   Temperature_C       1000 non-null   int64
 10  Weather             1000 non-null   object
 11  Weekend             1000 non-null   object
 12  Holiday             1000 non-null   object
 13  Discount_Percent    1000 non-null   int64
 14  Customers           1000 non-null   int64
 15  Waste_Amount_kg     1000 non-null   float64
dtypes: float64(1), int64(6), object(9)
memory usage: 125.1+ KB

Shape:
(1000, 16)

Columns:
['Restaurant_ID', 'Restaurant_Name', 'City', 'Cuisine', 'Food_Item', 'Date', 'Prepared_Quantity', 'Sold_Quantity', 'Remaining_Quantity', 'Temperature_C', 'Weather', 'Weekend', 'Holiday', 'Discount_Percent', 'Customers', 'Waste_Amount_kg']

Data types:
Restaurant_ID          object
Restaurant_Name        object
City                   object
Cuisine                object
Food_Item              object
Date                   object
Prepared_Quantity       int64
Sold_Quantity           int64
Remaining_Quantity      int64
Temperature_C           int64
Weather                object
Weekend                object
Holiday                object
Discount_Percent        int64
Customers               int64
Waste_Amount_kg       float64
dtype: object

Statistical description:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Restaurant_ID,1000,5,R002,216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Restaurant_Name,1000,5,Urban Bites,216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,1000,5,Bengaluru,216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cuisine,1000,4,North Indian,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Food_Item,1000,12,Pizza,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,1000,336,2025-01-28,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Prepared_Quantity,1000.0,NaN,NaN,NaN,174.901,72.412933,50.0,111.0,177.0,239.0,300.0
Sold_Quantity,1000.0,NaN,NaN,NaN,139.04,61.215797,18.0,86.0,139.0,189.0,294.0
Remaining_Quantity,1000.0,NaN,NaN,NaN,35.861,24.186622,0.0,17.0,33.0,53.0,112.0
Temperature_C,1000.0,NaN,NaN,NaN,31.218,5.480375,22.0,26.0,32.0,36.0,40.0
Weather,1000,3,Sunny,515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weekend,1000,2,No,723,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Holiday,1000,2,No,929,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount_Percent,1000.0,NaN,NaN,NaN,13.06,8.634869,0.0,5.0,15.0,20.0,25.0
Customers,1000.0,NaN,NaN,NaN,98.848,55.011591,11.0,56.0,90.0,128.25,320.0
Waste_Amount_kg,1000.0,NaN,NaN,NaN,9.49585,6.696288,0.0,4.385,8.375,14.01,34.06

Missing values:

Restaurant_ID         0
Restaurant_Name       0
City                  0
Cuisine               0
Food_Item             0
Date                  0
Prepared_Quantity     0
Sold_Quantity         0
Remaining_Quantity    0
Temperature_C         0
Weather               0
Weekend               0
Holiday               0
Discount_Percent      0
Customers             0
Waste_Amount_kg       0
dtype: int64

Duplicate rows:
0

Restaurant names:

Restaurant_Name
Urban Bites     216
Spice Garden    211
Food Hub        200
Ocean Treat     191
Green Bowl      182
Name: count, dtype: int64

Cities:

City
Bengaluru     216
Chennai       211
Coimbatore    200
Hyderabad     191
Mumbai        182
Name: count, dtype: int64

Cuisine types:

Cuisine
North Indian    256
South Indian    255
Chinese         247
Italian         242
Name: count, dtype: int64

Food items:

Food_Item
Pizza                   122
Pasta                   120
Naan                     95
Noodles                  92
Paneer Butter Masala     85
Fried Rice               79
Manchurian               76
Biryani                  76
Dosa                     68
Idli                     65
Pongal                   62
Meals                    60
Name: count, dtype: int64

Weather conditions:

Weather
Sunny     515
Cloudy    256
Rainy     229
Name: count, dtype: int64

Weekend status:

Weekend
No     723
Yes    277
Name: count, dtype: int64

Holiday status:

Holiday
No     929
Yes     71
Name: count, dtype: int64

Top restaurants based on food waste:

Restaurant_Name
Spice Garden    2058.37
Urban Bites     1925.83
Ocean Treat     1925.45
Food Hub        1887.74
Green Bowl      1698.46
Name: Waste_Amount_kg, dtype: float64

Top cities based on food waste:

City
Chennai       2058.37
Bengaluru     1925.83
Hyderabad     1925.45
Coimbatore    1887.74
Mumbai        1698.46
Name: Waste_Amount_kg, dtype: float64

Top food items based on food waste:

Food_Item
Pasta                   1217.42
Pizza                   1169.46
Noodles                  941.37
Naan                     877.92
Manchurian               787.13
Paneer Butter Masala     730.63
Biryani                  721.16
Idli                     704.77
Dosa                     671.38
Fried Rice               617.72
Meals                    552.17
Pongal                   504.72
Name: Waste_Amount_kg, dtype: float64

Correlation:

,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Discount_Percent,Customers,Waste_Amount_kg
Prepared_Quantity,1.000000,0.948157,0.594160,-0.024493,-0.018582,0.769898,0.564823
Sold_Quantity,0.948157,1.000000,0.307735,-0.012999,0.098393,0.805486,0.292245
Remaining_Quantity,0.594160,0.307735,1.000000,-0.040430,-0.304663,0.266351,0.951373
Temperature_C,-0.024493,-0.012999,-0.040430,1.000000,0.016455,-0.029530,-0.044988
Discount_Percent,-0.018582,0.098393,-0.304663,0.016455,1.000000,0.059131,-0.282863
Customers,0.769898,0.805486,0.266351,-0.029530,0.059131,1.000000,0.240449
Waste_Amount_kg,0.564823,0.292245,0.951373,-0.044988,-0.282863,0.240449,1.000000

Calculated Remaining Quantity:

   Prepared_Quantity  Sold_Quantity  Remaining_Quantity_Calculated
0                107            102                              5
1                229            198                             31
2                 89             89                              0
3                191            175                             16
4                147            113                             34

Waste Percentage:

  Restaurant_Name  Prepared_Quantity  Waste_Amount_kg  Waste_Percentage
0    Spice Garden                107             1.09          1.018692
1      Green Bowl                229             5.61          2.449782
2     Urban Bites                 89             0.00          0.000000
3        Food Hub                191             4.68          2.450262
4     Ocean Treat                147             9.87          6.714286

CSV, Excel and JSON files created successfully.