In [3]:
import os
import pandas as pd
import numpy as np

path = "/content/Food_Waste_Prediction_Dataset.csv"

print("Dataset path:", path)

df = pd.read_csv(path)

print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nDataset information:")
df.info()

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nStatistical description:")
display(df.describe())

print("\nMissing values:")
display(df.isnull().sum())

df = df.dropna(how="all")

df = df.drop_duplicates()

print("\nDataset after removing blank rows and duplicates:")
print(df.shape)

df["Remaining_Quantity"] = (
    df["Prepared_Quantity"] - df["Sold_Quantity"]
)

print("\nRemaining Quantity:")
display(
    df[
        [
            "Prepared_Quantity",
            "Sold_Quantity",
            "Remaining_Quantity"
        ]
    ].head()
)

df["Waste_Percentage"] = (
    df["Waste_Amount_kg"] /
    df["Prepared_Quantity"]
) * 100

print("\nWaste Percentage:")
display(
    df[
        [
            "Restaurant_Name",
            "Prepared_Quantity",
            "Waste_Amount_kg",
            "Waste_Percentage"
        ]
    ].head()
)

print("\nRestaurant-wise Food Waste:")
display(
    df.groupby("Restaurant_Name")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
)

print("\nCity-wise Food Waste:")
display(
    df.groupby("City")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
)

print("\nFood-item-wise Food Waste:")
display(
    df.groupby("Food_Item")["Waste_Amount_kg"]
    .sum()
    .sort_values(ascending=False)
)

df["Date"] = pd.to_datetime(df["Date"])

print("\nFood Waste Trend:")
display(
    df.groupby("Date")["Waste_Amount_kg"]
    .sum()
)

print("\nCorrelation:")
display(
    df.corr(numeric_only=True)
)

df.to_csv(
    "Food_Waste_Cleaned.csv",
    index=False
)

df.to_excel(
    "Food_Waste_Cleaned.xlsx",
    index=False
)

df.to_json(
    "Food_Waste_Cleaned.json",
    orient="records",
    indent=4
)

print("\nCSV, Excel and JSON files created successfully.")

Dataset path: /content/Food_Waste_Prediction_Dataset.csv

First 5 rows:

,Restaurant_ID,Restaurant_Name,City,Cuisine,Food_Item,Date,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Weather,Weekend,Holiday,Discount_Percent,Customers,Waste_Amount_kg
0,R001,Spice Garden,Chennai,South Indian,Pongal,2025-05-06,107,102,5,25,Cloudy,No,No,20,121,1.09
1,R005,Green Bowl,Mumbai,South Indian,Dosa,2025-11-29,229,198,31,29,Sunny,Yes,No,10,102,5.61
2,R002,Urban Bites,Bengaluru,Italian,Pasta,2025-05-23,89,89,0,32,Sunny,No,No,15,54,0.00
3,R004,Food Hub,Coimbatore,South Indian,Meals,2025-02-10,191,175,16,33,Cloudy,No,No,25,195,4.68
4,R003,Ocean Treat,Hyderabad,South Indian,Dosa,2025-02-21,147,113,34,33,Sunny,No,No,10,53,9.87

Last 5 rows:

,Restaurant_ID,Restaurant_Name,City,Cuisine,Food_Item,Date,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Weather,Weekend,Holiday,Discount_Percent,Customers,Waste_Amount_kg
995,R004,Food Hub,Coimbatore,South Indian,Dosa,2025-01-18,263,197,66,27,Rainy,Yes,No,5,129,17.82
996,R004,Food Hub,Coimbatore,Italian,Pasta,2025-03-07,152,99,53,29,Cloudy,No,No,0,77,15.02
997,R001,Spice Garden,Chennai,South Indian,Idli,2025-07-01,293,267,26,35,Cloudy,No,No,25,135,5.96
998,R004,Food Hub,Coimbatore,North Indian,Biryani,2025-04-04,235,164,71,38,Sunny,No,No,0,95,17.36
999,R004,Food Hub,Coimbatore,North Indian,Biryani,2025-10-29,121,92,29,25,Sunny,No,No,15,72,8.00

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Restaurant_ID       1000 non-null   object
 1   Restaurant_Name     1000 non-null   object
 2   City                1000 non-null   object
 3   Cuisine             1000 non-null   object
 4   Food_Item           1000 non-null   object
 5   Date                1000 non-null   object
 6   Prepared_Quantity   1000 non-null   int64
 7   Sold_Quantity       1000 non-null   int64
 8   Remaining_Quantity  1000 non-null   int64
 9   Temperature_C       1000 non-null   int64
 10  Weather             1000 non-null   object
 11  Weekend             1000 non-null   object
 12  Holiday             1000 non-null   object
 13  Discount_Percent    1000 non-null   int64
 14  Customers           1000 non-null   int64
 15  Waste_Amount_kg     1000 non-null   float64
dtypes: float64(1), int64(6), object(9)
memory usage: 125.1+ KB

Shape:
(1000, 16)

Columns:
['Restaurant_ID', 'Restaurant_Name', 'City', 'Cuisine', 'Food_Item', 'Date', 'Prepared_Quantity', 'Sold_Quantity', 'Remaining_Quantity', 'Temperature_C', 'Weather', 'Weekend', 'Holiday', 'Discount_Percent', 'Customers', 'Waste_Amount_kg']

Data types:
Restaurant_ID          object
Restaurant_Name        object
City                   object
Cuisine                object
Food_Item              object
Date                   object
Prepared_Quantity       int64
Sold_Quantity           int64
Remaining_Quantity      int64
Temperature_C           int64
Weather                object
Weekend                object
Holiday                object
Discount_Percent        int64
Customers               int64
Waste_Amount_kg       float64
dtype: object

Statistical description:

,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Discount_Percent,Customers,Waste_Amount_kg
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,174.901000,139.040000,35.861000,31.218000,13.060000,98.848000,9.495850
std,72.412933,61.215797,24.186622,5.480375,8.634869,55.011591,6.696288
min,50.000000,18.000000,0.000000,22.000000,0.000000,11.000000,0.000000
25%,111.000000,86.000000,17.000000,26.000000,5.000000,56.000000,4.385000
50%,177.000000,139.000000,33.000000,32.000000,15.000000,90.000000,8.375000
75%,239.000000,189.000000,53.000000,36.000000,20.000000,128.250000,14.010000
max,300.000000,294.000000,112.000000,40.000000,25.000000,320.000000,34.060000

Missing values:

Restaurant_ID         0
Restaurant_Name       0
City                  0
Cuisine               0
Food_Item             0
Date                  0
Prepared_Quantity     0
Sold_Quantity         0
Remaining_Quantity    0
Temperature_C         0
Weather               0
Weekend               0
Holiday               0
Discount_Percent      0
Customers             0
Waste_Amount_kg       0
dtype: int64

Dataset after removing blank rows and duplicates:
(1000, 16)

Remaining Quantity:

   Prepared_Quantity  Sold_Quantity  Remaining_Quantity
0                107            102                   5
1                229            198                  31
2                 89             89                   0
3                191            175                  16
4                147            113                  34

Waste Percentage:

  Restaurant_Name  Prepared_Quantity  Waste_Amount_kg  Waste_Percentage
0    Spice Garden                107             1.09          1.018692
1      Green Bowl                229             5.61          2.449782
2     Urban Bites                 89             0.00          0.000000
3        Food Hub                191             4.68          2.450262
4     Ocean Treat                147             9.87          6.714286

Restaurant-wise Food Waste:

Restaurant_Name
Spice Garden    2058.37
Urban Bites     1925.83
Ocean Treat     1925.45
Food Hub        1887.74
Green Bowl      1698.46
Name: Waste_Amount_kg, dtype: float64

City-wise Food Waste:

City
Chennai       2058.37
Bengaluru     1925.83
Hyderabad     1925.45
Coimbatore    1887.74
Mumbai        1698.46
Name: Waste_Amount_kg, dtype: float64

Food-item-wise Food Waste:

Food_Item
Pasta                   1217.42
Pizza                   1169.46
Noodles                  941.37
Naan                     877.92
Manchurian               787.13
Paneer Butter Masala     730.63
Biryani                  721.16
Idli                     704.77
Dosa                     671.38
Fried Rice               617.72
Meals                    552.17
Pongal                   504.72
Name: Waste_Amount_kg, dtype: float64

Food Waste Trend:

Date
2025-01-02     7.08
2025-01-03    96.40
2025-01-04    32.38
2025-01-05    11.60
2025-01-06    22.01
              ...
2025-12-27     9.73
2025-12-28    21.66
2025-12-29    30.16
2025-12-30    21.79
2025-12-31    31.75
Name: Waste_Amount_kg, Length: 336, dtype: float64

Correlation:

,Prepared_Quantity,Sold_Quantity,Remaining_Quantity,Temperature_C,Discount_Percent,Customers,Waste_Amount_kg,Waste_Percentage
Prepared_Quantity,1.000000,0.948157,0.594160,-0.024493,-0.018582,0.769898,0.564823,-0.034199
Sold_Quantity,0.948157,1.000000,0.307735,-0.012999,0.098393,0.805486,0.292245,-0.296290
Remaining_Quantity,0.594160,0.307735,1.000000,-0.040430,-0.304663,0.266351,0.951373,0.647515
Temperature_C,-0.024493,-0.012999,-0.040430,1.000000,0.016455,-0.029530,-0.044988,-0.039397
Discount_Percent,-0.018582,0.098393,-0.304663,0.016455,1.000000,0.059131,-0.282863,-0.302086
Customers,0.769898,0.805486,0.266351,-0.029530,0.059131,1.000000,0.240449,-0.235285
Waste_Amount_kg,0.564823,0.292245,0.951373,-0.044988,-0.282863,0.240449,1.000000,0.709032
Waste_Percentage,-0.034199,-0.296290,0.647515,-0.039397,-0.302086,-0.235285,0.709032,1.000000

CSV, Excel and JSON files created successfully.